name: 🪐 Nexus Hub | Bug
description: File a bug report.
title: "[Nexus Hub | Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: dropdown
    id: devices
    attributes:
      label: What devices are you seeing the problem on?
      multiple: true
      options:
        - Mobile
        - Dekstop
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Upload any screenshot here, it will help us identify the problem!
    validations:
      required: false
