name: 🪐 Nexus Hub | Report a Bug
description: Reporting bugs helps us improve Nexus Hub
title: "[Nexus-Hub Bug]: "
labels: "bug"

body:
  - type: textarea
    attributes:
      label: Bug Description
      description: The more details you provide, the faster we can identify the bug!
      placeholder: Nexus Hub is not working on a specific game.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce the bug?
      placeholder: |
        1. Inject Nexus Hub
        2. Wait until it loads
        3. Observe the behavior
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Behavior
      description: What should Nexus Hub do instead?
      placeholder: Nexus Hub should work as expected.
    validations:
      required: true

  - type: input
    attributes:
      label: Device
      description: On which device did you encounter this bug?
      placeholder: iPhone, Samsung, PC..
    validations:
      required: true

  - type: input
    attributes:
      label: Version Used
      description: Inject Nexus Hub → Type /console in the chat → You will see the version of Nexus Hub
      placeholder: "1.0"
    validations:
      required: true

  - type: textarea
    attributes:
      label: Screenshot(s) / Video
      description: This will help resolve the bug even faster
      placeholder: Click the 📎 icon to upload photo(s)/video(s)
    validations:
      required: false
