name: Lint Lua Scripts in NexusHub

on:
  push:
    paths:
      - 'NexusHub/**'
  pull_request:
    paths:
      - 'NexusHub/**'
  workflow_dispatch:

permissions:
  issues: write

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Lua and luacheck
        run: |
          sudo apt-get update
          sudo apt-get install -y lua5.3 liblua5.3-dev wget unzip
          
          wget https://luarocks.org/releases/luarocks-3.9.2.tar.gz
          tar zxpf luarocks-3.9.2.tar.gz
          cd luarocks-3.9.2
          ./configure --with-lua-include=/usr/include/lua5.3
          make
          sudo make install
          
          sudo luarocks install luacheck

      - name: Lint Lua files and collect errors
        run: |
          mkdir -p luacheck
          > luacheck/errors.txt
          find NexusHub -type f | while read file; do
            echo "Linting $file"
            if ! luacheck "$file" >> luacheck/errors.txt 2>&1; then
              echo "Errors in $file"
            fi
          done

      - name: Create or update issue if errors are found
        if: always()
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_TITLE: "Luacheck found issues in NexusHub/"
        run: |
          if [ -s luacheck/errors.txt ]; then
            body=$(cat luacheck/errors.txt | head -n 50 | sed 's/"/\\"/g' | sed 's/$/\\n/' | tr '\n' ' ' )
            issue_number=$(curl -s -H "Authorization: token $GH_TOKEN" \
              https://api.github.com/repos/${{ github.repository }}/issues \
              | jq ".[] | select(.title==\"$ISSUE_TITLE\") | .number")

            if [ "$issue_number" ]; then
              echo "Updating existing issue #$issue_number"
              curl -X PATCH -H "Authorization: token $GH_TOKEN" \
                   -H "Accept: application/vnd.github.v3+json" \
                   https://api.github.com/repos/${{ github.repository }}/issues/$issue_number \
                   -d "{\"body\": \"$body\"}"
            else
              echo "Creating new issue"
              curl -X POST -H "Authorization: token $GH_TOKEN" \
                   -H "Accept: application/vnd.github.v3+json" \
                   https://api.github.com/repos/${{ github.repository }}/issues \
                   -d "{\"title\": \"$ISSUE_TITLE\", \"body\": \"$body\"}"
            fi
          else
            echo "No errors found by luacheck."
          fi
